version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 8334:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Zelwix1234
    volumes:
      - ./drive:/var/opt/mssql/data
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: workguideserver
    ports:
      - 6001:80
    depends_on:
      - mssql
    volumes:
      - ./appsettings.Docker.json:/app/appsettings.json